const encounter = {
  rebels: [
    { id: 80820624, acted: false },
    { id: 85643018, acted: false },
    { id: 27962296, acted: true },
    { id: 44438667, acted: false },
    { id: 49986344, acted: false },
    { id: 79644805, acted: false },
  ],
  squadFull: false,
  enemy: [
    {
      hullType: 'Star Destroyer',
      Class: 'Imperial I',
      Silhouette: 8,
      Speed: 2,
      Handling: -3,
      defFore: 3,
      defPort: 3,
      defStarboard: 3,
      defAft: 2,
      Armor: 10,
      HT: 145,
      SS: 60,
      Manufacturer: 'Kuat Drive Yards',
      Massive: 2,
      Hyperdrive: 'Primary: Class 2, Backup: Class 8',
      Navicomputer: true,
      sensorRange: 'Long',
      image: 'imperial.jpg',
      shipsComplement: '37,085 officers, pilots, and enlisted crew',
      dockingBay: '72 starfighters',
      encumbranceCapacity: '15,000',
      passengerCapacity: '9,700',
      Consumables: 'Two years',
      Cost: '150,000,000',
      Restricted: true,
      Rarity: 7,
      HP: 2,
      Weapons: [
        {
          count: 10,
          linked: 1,
          mount: 'turret',
          position: 'port',
          type: 'Turbolaser (Heavy)',
          stats: {
            Name: 'Turbolaser (Heavy)',
            Skill: 'Gunnery',
            Range: 'Long',
            Dam: '11',
            Crit: '3',
            Price: '20,000',
            Restricted: 'Y',
            Rarity: 8,
            Size: '6-10',
            Qualities: 'Breach 4, Slow-Firing 2',
            Source: 'All Core',
          },
          selected: true,
          Index: 0,
          cooldown: 2,
        },
        {
          count: 10,
          linked: 1,
          mount: 'turret',
          position: 'starboard',
          type: 'Turbolaser (Heavy)',
          stats: {
            Name: 'Turbolaser (Heavy)',
            Skill: 'Gunnery',
            Range: 'Long',
            Dam: '11',
            Crit: '3',
            Price: '20,000',
            Restricted: 'Y',
            Rarity: 8,
            Size: '6-10',
            Qualities: 'Breach 4, Slow-Firing 2',
            Source: 'All Core',
          },
          selected: true,
          Index: 1,
          cooldown: 2,
        },
        {
          count: 10,
          linked: 1,
          mount: 'turret',
          position: 'dorsal',
          type: 'Turbolaser (Heavy)',
          stats: {
            Name: 'Turbolaser (Heavy)',
            Skill: 'Gunnery',
            Range: 'Long',
            Dam: '11',
            Crit: '3',
            Price: '20,000',
            Restricted: 'Y',
            Rarity: 8,
            Size: '6-10',
            Qualities: 'Breach 4, Slow-Firing 2',
            Source: 'All Core',
          },
          selected: true,
          Index: 2,
          cooldown: 2,
        },
        {
          count: 10,
          linked: 0,
          mount: 'forward',
          position: 'forward',
          type: 'Turbolaser (Light)',
          stats: {
            Name: 'Turbolaser (Light)',
            Skill: 'Gunnery',
            Range: 'Medium',
            Dam: '9',
            Crit: '3',
            Price: '12,000',
            Restricted: 'Y',
            Rarity: 7,
            Size: '5-10',
            Qualities: 'Breach 2, Slow-Firing 1',
            Source: 'All Core',
          },
          selected: false,
          Index: 3,
          cooldown: 3,
        },
        {
          count: 10,
          linked: 0,
          mount: 'port',
          position: 'port',
          type: 'Turbolaser (Light)',
          stats: {
            Name: 'Turbolaser (Light)',
            Skill: 'Gunnery',
            Range: 'Medium',
            Dam: '9',
            Crit: '3',
            Price: '12,000',
            Restricted: 'Y',
            Rarity: 7,
            Size: '5-10',
            Qualities: 'Breach 2, Slow-Firing 1',
            Source: 'All Core',
          },
        },
        {
          count: 10,
          linked: 0,
          mount: 'starboard',
          position: 'starboard',
          type: 'Turbolaser (Light)',
          stats: {
            Name: 'Turbolaser (Light)',
            Skill: 'Gunnery',
            Range: 'Medium',
            Dam: '9',
            Crit: '3',
            Price: '12,000',
            Restricted: 'Y',
            Rarity: 7,
            Size: '5-10',
            Qualities: 'Breach 2, Slow-Firing 1',
            Source: 'All Core',
          },
        },
        {
          count: 10,
          linked: 0,
          mount: 'turret',
          position: 'port',
          type: 'Ion Cannon (Battleship)',
          stats: {
            Name: 'Ion Cannon (Battleship)',
            Skill: 'Gunnery',
            Range: 'Medium',
            Dam: '9',
            Crit: '4',
            Price: '10,000',
            Restricted: 'N',
            Rarity: 8,
            Size: '8-10',
            Qualities: 'Breach 3, Ion, Slow-Firing 2',
            Source: 'SWA/F02',
          },
          selected: false,
          Index: 6,
          cooldown: 3,
        },
        {
          count: 10,
          linked: 0,
          mount: 'turret',
          position: 'starboard',
          type: 'Ion Cannon (Battleship)',
          stats: {
            Name: 'Ion Cannon (Battleship)',
            Skill: 'Gunnery',
            Range: 'Medium',
            Dam: '9',
            Crit: '4',
            Price: '10,000',
            Restricted: 'N',
            Rarity: 8,
            Size: '8-10',
            Qualities: 'Breach 3, Ion, Slow-Firing 2',
            Source: 'SWA/F02',
          },
          selected: false,
          Index: 7,
          cooldown: 3,
        },
        {
          count: 10,
          linked: 1,
          mount: 'turret',
          position: 'ventral',
          type: 'Ion Cannon (Battleship)',
          stats: {
            Name: 'Ion Cannon (Battleship)',
            Skill: 'Gunnery',
            Range: 'Medium',
            Dam: '9',
            Crit: '4',
            Price: '10,000',
            Restricted: 'N',
            Rarity: 8,
            Size: '8-10',
            Qualities: 'Breach 3, Ion, Slow-Firing 2',
            Source: 'SWA/F02',
          },
          selected: false,
          Index: 8,
          cooldown: 3,
        },
        {
          count: 15,
          linked: 0,
          mount: 'port',
          position: 'port',
          type: 'Ion Cannon (Medium)',
          stats: {
            Name: 'Ion Cannon (Medium)',
            Skill: 'Gunnery',
            Range: 'Short',
            Dam: '6',
            Crit: '4',
            Price: '6,000',
            Restricted: 'N',
            Rarity: 6,
            Size: '5-10',
            Qualities: 'Ion',
            Source: 'All Core',
          },
        },
        {
          count: 15,
          linked: 0,
          mount: 'starboard',
          position: 'starboard',
          type: 'Ion Cannon (Medium)',
          stats: {
            Name: 'Ion Cannon (Medium)',
            Skill: 'Gunnery',
            Range: 'Short',
            Dam: '6',
            Crit: '4',
            Price: '6,000',
            Restricted: 'N',
            Rarity: 6,
            Size: '5-10',
            Qualities: 'Ion',
            Source: 'All Core',
          },
        },
        {
          count: 10,
          linked: 0,
          mount: 'turret',
          position: 'ventral',
          type: 'Tractor Beam (Heavy)',
          stats: {
            Name: 'Tractor Beam (Heavy)',
            Skill: 'Gunnery',
            Range: 'Short',
            Dam: '—',
            Crit: '—',
            Price: '10,000',
            Restricted: 'N',
            Rarity: 6,
            Size: '5-10',
            Qualities: 'Tractor 6',
            Source: 'All Core',
          },
          selected: false,
          Index: 11,
        },
      ],
      id: 371481,
      Name: 'Flag',
      curr_HT: 145,
      curr_SS: 60,
      crits: [],
      acted: false,
    },
    {
      hullType: 'Star Destroyer',
      Class: 'Imperial I',
      Silhouette: 8,
      Speed: 2,
      Handling: -3,
      defFore: 0,
      defPort: 2,
      defStarboard: 0,
      defAft: 0,
      Armor: 10,
      HT: 145,
      SS: 60,
      Manufacturer: 'Kuat Drive Yards',
      Massive: 2,
      Hyperdrive: 'Primary: Class 2, Backup: Class 8',
      Navicomputer: true,
      sensorRange: 'Long',
      image: 'imperial.jpg',
      shipsComplement: '37,085 officers, pilots, and enlisted crew',
      dockingBay: '72 starfighters',
      encumbranceCapacity: '15,000',
      passengerCapacity: '9,700',
      Consumables: 'Two years',
      Cost: '150,000,000',
      Restricted: true,
      Rarity: 7,
      HP: 2,
      Weapons: [
        {
          count: 10,
          linked: 1,
          mount: 'turret',
          position: 'port',
          type: 'Turbolaser (Heavy)',
          stats: {
            Name: 'Turbolaser (Heavy)',
            Skill: 'Gunnery',
            Range: 'Long',
            Dam: '11',
            Crit: '3',
            Price: '20,000',
            Restricted: 'Y',
            Rarity: 8,
            Size: '6-10',
            Qualities: 'Breach 4, Slow-Firing 2',
            Source: 'All Core',
          },
          selected: false,
          Index: 0,
          cooldown: 5,
        },
        {
          count: 10,
          linked: 1,
          mount: 'turret',
          position: 'starboard',
          type: 'Turbolaser (Heavy)',
          stats: {
            Name: 'Turbolaser (Heavy)',
            Skill: 'Gunnery',
            Range: 'Long',
            Dam: '11',
            Crit: '3',
            Price: '20,000',
            Restricted: 'Y',
            Rarity: 8,
            Size: '6-10',
            Qualities: 'Breach 4, Slow-Firing 2',
            Source: 'All Core',
          },
          selected: false,
          Index: 1,
          cooldown: 2,
        },
        {
          count: 10,
          linked: 1,
          mount: 'turret',
          position: 'dorsal',
          type: 'Turbolaser (Heavy)',
          stats: {
            Name: 'Turbolaser (Heavy)',
            Skill: 'Gunnery',
            Range: 'Long',
            Dam: '11',
            Crit: '3',
            Price: '20,000',
            Restricted: 'Y',
            Rarity: 8,
            Size: '6-10',
            Qualities: 'Breach 4, Slow-Firing 2',
            Source: 'All Core',
          },
          selected: false,
          Index: 2,
          cooldown: 5,
        },
        {
          count: 10,
          linked: 0,
          mount: 'forward',
          position: 'forward',
          type: 'Turbolaser (Light)',
          stats: {
            Name: 'Turbolaser (Light)',
            Skill: 'Gunnery',
            Range: 'Medium',
            Dam: '9',
            Crit: '3',
            Price: '12,000',
            Restricted: 'Y',
            Rarity: 7,
            Size: '5-10',
            Qualities: 'Breach 2, Slow-Firing 1',
            Source: 'All Core',
          },
          selected: true,
          Index: 3,
          cooldown: 3,
        },
        {
          count: 10,
          linked: 0,
          mount: 'port',
          position: 'port',
          type: 'Turbolaser (Light)',
          stats: {
            Name: 'Turbolaser (Light)',
            Skill: 'Gunnery',
            Range: 'Medium',
            Dam: '9',
            Crit: '3',
            Price: '12,000',
            Restricted: 'Y',
            Rarity: 7,
            Size: '5-10',
            Qualities: 'Breach 2, Slow-Firing 1',
            Source: 'All Core',
          },
          selected: true,
          Index: 4,
          cooldown: 4,
        },
        {
          count: 10,
          linked: 0,
          mount: 'starboard',
          position: 'starboard',
          type: 'Turbolaser (Light)',
          stats: {
            Name: 'Turbolaser (Light)',
            Skill: 'Gunnery',
            Range: 'Medium',
            Dam: '9',
            Crit: '3',
            Price: '12,000',
            Restricted: 'Y',
            Rarity: 7,
            Size: '5-10',
            Qualities: 'Breach 2, Slow-Firing 1',
            Source: 'All Core',
          },
        },
        {
          count: 10,
          linked: 0,
          mount: 'turret',
          position: 'port',
          type: 'Ion Cannon (Battleship)',
          stats: {
            Name: 'Ion Cannon (Battleship)',
            Skill: 'Gunnery',
            Range: 'Medium',
            Dam: '9',
            Crit: '4',
            Price: '10,000',
            Restricted: 'N',
            Rarity: 8,
            Size: '8-10',
            Qualities: 'Breach 3, Ion, Slow-Firing 2',
            Source: 'SWA/F02',
          },
          selected: false,
          Index: 6,
          cooldown: 3,
        },
        {
          count: 10,
          linked: 0,
          mount: 'turret',
          position: 'starboard',
          type: 'Ion Cannon (Battleship)',
          stats: {
            Name: 'Ion Cannon (Battleship)',
            Skill: 'Gunnery',
            Range: 'Medium',
            Dam: '9',
            Crit: '4',
            Price: '10,000',
            Restricted: 'N',
            Rarity: 8,
            Size: '8-10',
            Qualities: 'Breach 3, Ion, Slow-Firing 2',
            Source: 'SWA/F02',
          },
          selected: false,
          Index: 7,
          cooldown: 3,
        },
        {
          count: 10,
          linked: 1,
          mount: 'turret',
          position: 'ventral',
          type: 'Ion Cannon (Battleship)',
          stats: {
            Name: 'Ion Cannon (Battleship)',
            Skill: 'Gunnery',
            Range: 'Medium',
            Dam: '9',
            Crit: '4',
            Price: '10,000',
            Restricted: 'N',
            Rarity: 8,
            Size: '8-10',
            Qualities: 'Breach 3, Ion, Slow-Firing 2',
            Source: 'SWA/F02',
          },
          selected: false,
          Index: 8,
          cooldown: 3,
        },
        {
          count: 15,
          linked: 0,
          mount: 'port',
          position: 'port',
          type: 'Ion Cannon (Medium)',
          stats: {
            Name: 'Ion Cannon (Medium)',
            Skill: 'Gunnery',
            Range: 'Short',
            Dam: '6',
            Crit: '4',
            Price: '6,000',
            Restricted: 'N',
            Rarity: 6,
            Size: '5-10',
            Qualities: 'Ion',
            Source: 'All Core',
          },
          selected: false,
          Index: 9,
        },
        {
          count: 15,
          linked: 0,
          mount: 'starboard',
          position: 'starboard',
          type: 'Ion Cannon (Medium)',
          stats: {
            Name: 'Ion Cannon (Medium)',
            Skill: 'Gunnery',
            Range: 'Short',
            Dam: '6',
            Crit: '4',
            Price: '6,000',
            Restricted: 'N',
            Rarity: 6,
            Size: '5-10',
            Qualities: 'Ion',
            Source: 'All Core',
          },
        },
        {
          count: 10,
          linked: 0,
          mount: 'turret',
          position: 'ventral',
          type: 'Tractor Beam (Heavy)',
          stats: {
            Name: 'Tractor Beam (Heavy)',
            Skill: 'Gunnery',
            Range: 'Short',
            Dam: '—',
            Crit: '—',
            Price: '10,000',
            Restricted: 'N',
            Rarity: 6,
            Size: '5-10',
            Qualities: 'Tractor 6',
            Source: 'All Core',
          },
          selected: false,
          Index: 11,
        },
      ],
      id: 931355,
      Name: '',
      curr_HT: 125,
      curr_SS: 51,
      crits: [
        {
          difficulty: 2,
          name: 'Shields Down',
          desc:
            'Decrease defense in affected defense zone to 0 and all other defense zones by 1 point until repaired. If ship or vehicle has no defense, suffer 4 system strain.',
        },
        {
          difficulty: 2,
          name: 'Engine Damaged',
          desc: 'Ship or vehicle ’s maximum speed reduced by 1, to a minimum of 1, until repaired.',
        },
        {
          difficulty: 2,
          name: 'Shields Failing ',
          desc:
            'Decrease defense in all defense zones by 1 until repaired. If ship or vehicle has no defense, suffer 2 system strain.',
        },
        {
          difficulty: 1,
          name: 'Knocked Off Course',
          desc:
            'On next turn, pilot cannot execute any maneuvers. Instead, must make a Piloting check to regain bearings and resume course. Difficulty depends on current speed',
        },
        {
          difficulty: 2,
          name: 'Power Fluctuations',
          desc: 'Pilot cannot voluntarily inflict system strain on the ship until repaired.',
        },
        {
          difficulty: 1,
          name: 'Component Hit',
          desc:
            'Component from Small Ship Components or Large Ship Components (see tables below) is rendered inoperable until end of next round.',
        },
      ],
      acted: false,
    },
    {
      hullType: 'Cruiser',
      Class: 'Vindicator',
      Silhouette: 7,
      Speed: 3,
      Handling: -1,
      defFore: 4,
      defPort: 2,
      defStarboard: 2,
      defAft: 1,
      Armor: 6,
      HT: 85,
      SS: 55,
      Manufacturer: 'Sienar Fleet Systems',
      Massive: 1,
      Hyperdrive: 'Primary: Class 2, Backup: Class 12',
      Navicomputer: true,
      sensorRange: 'Long',
      image: 'vindicator.jpg',
      shipsComplement: '2,551 officers, pilots, and enlisted crew.',
      dockingBay: '24 starfighters',
      encumbranceCapacity: '7,500',
      passengerCapacity: '400 troops',
      Consumables: 'Sixteen months',
      Cost: '10,400,000',
      Restricted: true,
      Rarity: 8,
      HP: 0,
      Weapons: [
        {
          count: 5,
          linked: 0,
          mount: 'turret',
          position: 'dorsal',
          type: 'Turbolaser (Medium)',
          stats: {
            Name: 'Turbolaser (Medium)',
            Skill: 'Gunnery',
            Range: 'Long',
            Dam: '10',
            Crit: '3',
            Price: '15,000',
            Restricted: 'Y',
            Rarity: 7,
            Size: '6-10',
            Qualities: 'Breach 3, Slow-Firing 1',
            Source: 'All Core',
          },
          selected: false,
          Index: 0,
          cooldown: 2,
        },
        {
          count: 5,
          linked: 0,
          mount: 'turret',
          position: 'port',
          type: 'Turbolaser (Medium)',
          stats: {
            Name: 'Turbolaser (Medium)',
            Skill: 'Gunnery',
            Range: 'Long',
            Dam: '10',
            Crit: '3',
            Price: '15,000',
            Restricted: 'Y',
            Rarity: 7,
            Size: '6-10',
            Qualities: 'Breach 3, Slow-Firing 1',
            Source: 'All Core',
          },
          selected: false,
          Index: 1,
          cooldown: 2,
        },
        {
          count: 5,
          linked: 0,
          mount: 'turret',
          position: 'starboard',
          type: 'Turbolaser (Medium)',
          stats: {
            Name: 'Turbolaser (Medium)',
            Skill: 'Gunnery',
            Range: 'Long',
            Dam: '10',
            Crit: '3',
            Price: '15,000',
            Restricted: 'Y',
            Rarity: 7,
            Size: '6-10',
            Qualities: 'Breach 3, Slow-Firing 1',
            Source: 'All Core',
          },
          selected: false,
          Index: 2,
          cooldown: 2,
        },
        {
          count: 5,
          linked: 3,
          mount: 'turret',
          position: 'port',
          type: 'Turbolaser (Light)',
          stats: {
            Name: 'Turbolaser (Light)',
            Skill: 'Gunnery',
            Range: 'Medium',
            Dam: '9',
            Crit: '3',
            Price: '12,000',
            Restricted: 'Y',
            Rarity: 7,
            Size: '5-10',
            Qualities: 'Breach 2, Slow-Firing 1',
            Source: 'All Core',
          },
          selected: false,
          Index: 3,
        },
        {
          count: 5,
          linked: 3,
          mount: 'turret',
          position: 'starboard',
          type: 'Turbolaser (Light)',
          stats: {
            Name: 'Turbolaser (Light)',
            Skill: 'Gunnery',
            Range: 'Medium',
            Dam: '9',
            Crit: '3',
            Price: '12,000',
            Restricted: 'Y',
            Rarity: 7,
            Size: '5-10',
            Qualities: 'Breach 2, Slow-Firing 1',
            Source: 'All Core',
          },
          selected: false,
          Index: 4,
        },
        {
          count: 6,
          linked: 0,
          mount: 'forward',
          position: 'forward',
          type: 'Point Defense Laser Cannon',
          stats: {
            Name: 'Point Defense Laser Cannon',
            Skill: 'Gunnery',
            Range: 'Close',
            Dam: '5',
            Crit: '3',
            Price: '5,500',
            Restricted: 'N',
            Rarity: 4,
            Size: '3-10',
            Qualities: 'Accurate 1',
            Source: 'All Core',
          },
          selected: false,
          Index: 5,
        },
        {
          count: 8,
          linked: 0,
          mount: 'port',
          position: 'port',
          type: 'Point Defense Laser Cannon',
          stats: {
            Name: 'Point Defense Laser Cannon',
            Skill: 'Gunnery',
            Range: 'Close',
            Dam: '5',
            Crit: '3',
            Price: '5,500',
            Restricted: 'N',
            Rarity: 4,
            Size: '3-10',
            Qualities: 'Accurate 1',
            Source: 'All Core',
          },
        },
        {
          count: 8,
          linked: 0,
          mount: 'starboard',
          position: 'starboard',
          type: 'Point Defense Laser Cannon',
          stats: {
            Name: 'Point Defense Laser Cannon',
            Skill: 'Gunnery',
            Range: 'Close',
            Dam: '5',
            Crit: '3',
            Price: '5,500',
            Restricted: 'N',
            Rarity: 4,
            Size: '3-10',
            Qualities: 'Accurate 1',
            Source: 'All Core',
          },
        },
        {
          count: 8,
          linked: 0,
          mount: 'aft',
          position: 'aft',
          type: 'Point Defense Laser Cannon',
          stats: {
            Name: 'Point Defense Laser Cannon',
            Skill: 'Gunnery',
            Range: 'Close',
            Dam: '5',
            Crit: '3',
            Price: '5,500',
            Restricted: 'N',
            Rarity: 4,
            Size: '3-10',
            Qualities: 'Accurate 1',
            Source: 'All Core',
          },
        },
        {
          count: 3,
          linked: 0,
          mount: 'hull',
          position: 'ventral',
          type: 'Tractor Beam (Heavy)',
          stats: {
            Name: 'Tractor Beam (Heavy)',
            Skill: 'Gunnery',
            Range: 'Short',
            Dam: '—',
            Crit: '—',
            Price: '10,000',
            Restricted: 'N',
            Rarity: 6,
            Size: '5-10',
            Qualities: 'Tractor 6',
            Source: 'All Core',
          },
        },
      ],
      id: 769222,
      Name: '',
      curr_HT: 0,
      curr_SS: 55,
      crits: [],
      acted: false,
    },
    {
      hullType: 'Cruiser',
      Class: 'Vindicator',
      Silhouette: 7,
      Speed: 3,
      Handling: -1,
      defFore: 3,
      defPort: 2,
      defStarboard: 2,
      defAft: 2,
      Armor: 6,
      HT: 85,
      SS: 55,
      Manufacturer: 'Sienar Fleet Systems',
      Massive: 1,
      Hyperdrive: 'Primary: Class 2, Backup: Class 12',
      Navicomputer: true,
      sensorRange: 'Long',
      image: 'vindicator.jpg',
      shipsComplement: '2,551 officers, pilots, and enlisted crew.',
      dockingBay: '24 starfighters',
      encumbranceCapacity: '7,500',
      passengerCapacity: '400 troops',
      Consumables: 'Sixteen months',
      Cost: '10,400,000',
      Restricted: true,
      Rarity: 8,
      HP: 0,
      Weapons: [
        {
          count: 5,
          linked: 0,
          mount: 'turret',
          position: 'dorsal',
          type: 'Turbolaser (Medium)',
          stats: {
            Name: 'Turbolaser (Medium)',
            Skill: 'Gunnery',
            Range: 'Long',
            Dam: '10',
            Crit: '3',
            Price: '15,000',
            Restricted: 'Y',
            Rarity: 7,
            Size: '6-10',
            Qualities: 'Breach 3, Slow-Firing 1',
            Source: 'All Core',
          },
          selected: false,
          Index: 0,
          cooldown: 3,
        },
        {
          count: 5,
          linked: 0,
          mount: 'turret',
          position: 'port',
          type: 'Turbolaser (Medium)',
          stats: {
            Name: 'Turbolaser (Medium)',
            Skill: 'Gunnery',
            Range: 'Long',
            Dam: '10',
            Crit: '3',
            Price: '15,000',
            Restricted: 'Y',
            Rarity: 7,
            Size: '6-10',
            Qualities: 'Breach 3, Slow-Firing 1',
            Source: 'All Core',
          },
          selected: false,
          Index: 1,
          cooldown: 3,
        },
        {
          count: 5,
          linked: 0,
          mount: 'turret',
          position: 'starboard',
          type: 'Turbolaser (Medium)',
          stats: {
            Name: 'Turbolaser (Medium)',
            Skill: 'Gunnery',
            Range: 'Long',
            Dam: '10',
            Crit: '3',
            Price: '15,000',
            Restricted: 'Y',
            Rarity: 7,
            Size: '6-10',
            Qualities: 'Breach 3, Slow-Firing 1',
            Source: 'All Core',
          },
          selected: true,
          Index: 2,
          cooldown: 1,
        },
        {
          count: 5,
          linked: 3,
          mount: 'turret',
          position: 'port',
          type: 'Turbolaser (Light)',
          stats: {
            Name: 'Turbolaser (Light)',
            Skill: 'Gunnery',
            Range: 'Medium',
            Dam: '9',
            Crit: '3',
            Price: '12,000',
            Restricted: 'Y',
            Rarity: 7,
            Size: '5-10',
            Qualities: 'Breach 2, Slow-Firing 1',
            Source: 'All Core',
          },
          selected: true,
          Index: 3,
        },
        {
          count: 5,
          linked: 3,
          mount: 'turret',
          position: 'starboard',
          type: 'Turbolaser (Light)',
          stats: {
            Name: 'Turbolaser (Light)',
            Skill: 'Gunnery',
            Range: 'Medium',
            Dam: '9',
            Crit: '3',
            Price: '12,000',
            Restricted: 'Y',
            Rarity: 7,
            Size: '5-10',
            Qualities: 'Breach 2, Slow-Firing 1',
            Source: 'All Core',
          },
          selected: false,
          Index: 4,
        },
        {
          count: 6,
          linked: 0,
          mount: 'forward',
          position: 'forward',
          type: 'Point Defense Laser Cannon',
          stats: {
            Name: 'Point Defense Laser Cannon',
            Skill: 'Gunnery',
            Range: 'Close',
            Dam: '5',
            Crit: '3',
            Price: '5,500',
            Restricted: 'N',
            Rarity: 4,
            Size: '3-10',
            Qualities: 'Accurate 1',
            Source: 'All Core',
          },
          selected: false,
          Index: 5,
        },
        {
          count: 8,
          linked: 0,
          mount: 'port',
          position: 'port',
          type: 'Point Defense Laser Cannon',
          stats: {
            Name: 'Point Defense Laser Cannon',
            Skill: 'Gunnery',
            Range: 'Close',
            Dam: '5',
            Crit: '3',
            Price: '5,500',
            Restricted: 'N',
            Rarity: 4,
            Size: '3-10',
            Qualities: 'Accurate 1',
            Source: 'All Core',
          },
          selected: false,
          Index: 6,
        },
        {
          count: 8,
          linked: 0,
          mount: 'starboard',
          position: 'starboard',
          type: 'Point Defense Laser Cannon',
          stats: {
            Name: 'Point Defense Laser Cannon',
            Skill: 'Gunnery',
            Range: 'Close',
            Dam: '5',
            Crit: '3',
            Price: '5,500',
            Restricted: 'N',
            Rarity: 4,
            Size: '3-10',
            Qualities: 'Accurate 1',
            Source: 'All Core',
          },
        },
        {
          count: 8,
          linked: 0,
          mount: 'aft',
          position: 'aft',
          type: 'Point Defense Laser Cannon',
          stats: {
            Name: 'Point Defense Laser Cannon',
            Skill: 'Gunnery',
            Range: 'Close',
            Dam: '5',
            Crit: '3',
            Price: '5,500',
            Restricted: 'N',
            Rarity: 4,
            Size: '3-10',
            Qualities: 'Accurate 1',
            Source: 'All Core',
          },
        },
        {
          count: 3,
          linked: 0,
          mount: 'hull',
          position: 'ventral',
          type: 'Tractor Beam (Heavy)',
          stats: {
            Name: 'Tractor Beam (Heavy)',
            Skill: 'Gunnery',
            Range: 'Short',
            Dam: '—',
            Crit: '—',
            Price: '10,000',
            Restricted: 'N',
            Rarity: 6,
            Size: '5-10',
            Qualities: 'Tractor 6',
            Source: 'All Core',
          },
        },
      ],
      id: 800601,
      Name: '',
      curr_HT: 0,
      curr_SS: 54,
      crits: [
        {
          difficulty: 1,
          name: 'Mechanical Stress',
          desc: 'Ship or vehicle suffers 1 system strain.',
        },
        {
          difficulty: 1,
          name: 'Knocked Off Course',
          desc:
            'On next turn, pilot cannot execute any maneuvers. Instead, must make a Piloting check to regain bearings and resume course. Difficulty depends on current speed',
        },
      ],
      acted: false,
    },
    {
      hullType: 'Corvette',
      Class: 'Vigil',
      Silhouette: 5,
      Speed: 3,
      Handling: -1,
      defFore: 2,
      defPort: 2,
      defStarboard: 2,
      defAft: 1,
      Armor: 5,
      HT: 55,
      SS: 35,
      Manufacturer: 'Kuat Drive Yards',
      Massive: 0,
      Hyperdrive: 'Primary: Class 2, Backup: Class 10',
      Navicomputer: true,
      sensorRange: 'Long',
      image: 'vigil.jpg',
      shipsComplement: '200 officers, enlisted, and troops',
      dockingBay: 'N/A',
      encumbranceCapacity: '1800',
      passengerCapacity: '200',
      Consumables: 'One year',
      Cost: '3,500,000',
      Restricted: true,
      Rarity: 5,
      HP: 0,
      Weapons: [
        {
          count: 3,
          linked: 1,
          mount: 'turret',
          position: 'dorsal',
          type: 'Turbolaser (Light)',
          stats: {
            Name: 'Turbolaser (Light)',
            Skill: 'Gunnery',
            Range: 'Medium',
            Dam: '9',
            Crit: '3',
            Price: '12,000',
            Restricted: 'Y',
            Rarity: 7,
            Size: '5-10',
            Qualities: 'Breach 2, Slow-Firing 1',
            Source: 'All Core',
          },
          selected: true,
          Index: 0,
          cooldown: 4,
        },
        {
          count: 3,
          linked: 1,
          mount: 'turret',
          position: 'dorsal',
          type: 'Laser Cannon (Heavy)',
          stats: {
            Name: 'Laser Cannon (Heavy)',
            Skill: 'Gunnery',
            Range: 'Short',
            Dam: '6',
            Crit: '3',
            Price: '7,500',
            Restricted: 'N',
            Rarity: 5,
            Size: '4-10',
            Qualities: '',
            Source: 'All Core',
          },
          selected: false,
          Index: 1,
        },
        {
          count: 1,
          linked: 0,
          mount: 'forward',
          position: 'forward',
          type: 'Tractor Beam (Medium)',
          stats: {
            Name: 'Tractor Beam (Medium)',
            Skill: 'Gunnery',
            Range: 'Short ',
            Dam: '—',
            Crit: '—',
            Price: '8,000',
            Restricted: 'N',
            Rarity: 5,
            Size: '5-10',
            Qualities: 'Tractor 4',
            Source: 'All Core',
          },
        },
      ],
      id: 711523,
      Name: '',
      curr_HT: 0,
      curr_SS: 35,
      crits: [{ difficulty: 1, name: 'Jostled', desc: 'All crew members suffer 1 strain.' }],
      acted: false,
    },
    {
      hullType: 'Corvette',
      Class: 'Raider I',
      Silhouette: 5,
      Speed: 4,
      Handling: -1,
      defFore: 2,
      defPort: 2,
      defStarboard: 2,
      defAft: 2,
      Armor: 5,
      HT: 45,
      SS: 25,
      Manufacturer: 'Kuat Drive Yards',
      Massive: 0,
      Hyperdrive: 'Primary: Class 2, Backup: Class 15',
      Navicomputer: true,
      sensorRange: 'Long',
      image: 'raider.png',
      shipsComplement: '15 officers, and 77 enlisted crew',
      dockingBay: 'N/A',
      encumbranceCapacity: '300',
      passengerCapacity: '30',
      Consumables: 'Three Months',
      Cost: '3,000,000',
      Restricted: true,
      Rarity: 7,
      HP: 2,
      Weapons: [
        {
          count: 1,
          linked: 1,
          mount: 'forward',
          position: 'forward',
          type: 'Turbolaser (Light)',
          stats: {
            Name: 'Turbolaser (Light)',
            Skill: 'Gunnery',
            Range: 'Medium',
            Dam: '9',
            Crit: '3',
            Price: '12,000',
            Restricted: 'Y',
            Rarity: 7,
            Size: '5-10',
            Qualities: 'Breach 2, Slow-Firing 1',
            Source: 'All Core',
          },
          selected: true,
          Index: 0,
          cooldown: 2,
        },
        {
          count: 3,
          linked: 1,
          mount: 'turret',
          position: 'port',
          type: 'Laser Cannon (Heavy)',
          stats: {
            Name: 'Laser Cannon (Heavy)',
            Skill: 'Gunnery',
            Range: 'Short',
            Dam: '6',
            Crit: '3',
            Price: '7,500',
            Restricted: 'N',
            Rarity: 5,
            Size: '4-10',
            Qualities: '',
            Source: 'All Core',
          },
          selected: false,
          Index: 1,
        },
        {
          count: 3,
          linked: 1,
          mount: 'turret',
          position: 'starboard',
          type: 'Laser Cannon (Heavy)',
          stats: {
            Name: 'Laser Cannon (Heavy)',
            Skill: 'Gunnery',
            Range: 'Short',
            Dam: '6',
            Crit: '3',
            Price: '7,500',
            Restricted: 'N',
            Rarity: 5,
            Size: '4-10',
            Qualities: '',
            Source: 'All Core',
          },
          selected: false,
          Index: 2,
        },
        {
          count: 1,
          linked: 0,
          mount: 'forward',
          position: 'forward',
          type: 'Ion Cannon (Battleship)',
          stats: {
            Name: 'Ion Cannon (Battleship)',
            Skill: 'Gunnery',
            Range: 'Medium',
            Dam: '9',
            Crit: '4',
            Price: '10,000',
            Restricted: 'N',
            Rarity: 8,
            Size: '8-10',
            Qualities: 'Breach 3, Ion, Slow-Firing 2',
            Source: 'SWA/F02',
          },
          selected: false,
          Index: 3,
          cooldown: 2,
        },
      ],
      id: 785456,
      Name: '',
      curr_HT: 3,
      curr_SS: 25,
      crits: [],
      acted: false,
    },
  ],
  turn: 4,
};

const praetor = {
  hullType: 'Star Battlecruiser',
  Class: 'Praetor II',
  Silhouette: 9,
  Speed: 2,
  Handling: -3,
  defFore: 4,
  defPort: 4,
  defStarboard: 0,
  defAft: 0,
  Armor: 11,
  HT: 185,
  SS: 95,
  image: 'praetor.jpg',
  Manufacturer: 'Kuat Drive Yards',
  Massive: 3,
  Hyperdrive: 'Primary: Class 2, Backup: Class 16',
  Navicomputer: 'Yes',
  sensorRange: 'Long',
  shipsComplement: '109,000 officers, pilots, and enlisted crew',
  dockingBay: '120 starfighters',
  encumbranceCapacity: '78,000',
  passengerCapacity: '14000 troops',
  Consumables: 'Three years',
  Cost: '700,000,000',
  Restricted: 'Y',
  Rarity: 9,
  HP: 1,
  Weapons: [
    {
      count: 30,
      linked: 3,
      mount: 'turret',
      position: 'port',
      type: 'Turbolaser (Heavy)',
      stats: {
        Name: 'Turbolaser (Heavy)',
        Skill: 'Gunnery',
        Range: 'Long',
        Dam: '11',
        Crit: '3',
        Price: '20,000',
        Restricted: 'Y',
        Rarity: 8,
        Size: '6-10',
        Qualities: 'Breach 4, Slow-Firing 2',
        Source: 'All Core',
      },
      selected: false,
      Index: 0,
      cooldown: 2,
    },
    {
      count: 30,
      linked: 3,
      mount: 'turret',
      position: 'starboard',
      type: 'Turbolaser (Heavy)',
      stats: {
        Name: 'Turbolaser (Heavy)',
        Skill: 'Gunnery',
        Range: 'Long',
        Dam: '11',
        Crit: '3',
        Price: '20,000',
        Restricted: 'Y',
        Rarity: 8,
        Size: '6-10',
        Qualities: 'Breach 4, Slow-Firing 2',
        Source: 'All Core',
      },
      selected: false,
      Index: 1,
      cooldown: 2,
    },
    {
      count: 20,
      linked: 1,
      mount: 'turret',
      position: 'dorsal',
      type: 'Turbolaser (Medium)',
      stats: {
        Name: 'Turbolaser (Medium)',
        Skill: 'Gunnery',
        Range: 'Long',
        Dam: '10',
        Crit: '3',
        Price: '15,000',
        Restricted: 'Y',
        Rarity: 7,
        Size: '6-10',
        Qualities: 'Breach 3, Slow-Firing 1',
        Source: 'All Core',
      },
      selected: false,
      Index: 2,
    },
    {
      count: 20,
      linked: 1,
      mount: 'turret',
      position: 'ventral',
      type: 'Turbolaser (Medium)',
      stats: {
        Name: 'Turbolaser (Medium)',
        Skill: 'Gunnery',
        Range: 'Long',
        Dam: '10',
        Crit: '3',
        Price: '15,000',
        Restricted: 'Y',
        Rarity: 7,
        Size: '6-10',
        Qualities: 'Breach 3, Slow-Firing 1',
        Source: 'All Core',
      },
      selected: false,
      Index: 3,
    },
    {
      count: 10,
      linked: 1,
      mod: {
        Range: 'Long',
      },
      mount: 'forward',
      position: 'forward',
      type: 'Ion Cannon (Battleship)',
      stats: {
        Name: 'Ion Cannon (Battleship)',
        Skill: 'Gunnery',
        Range: 'Long',
        Dam: '9',
        Crit: '4',
        Price: '10,000',
        Restricted: 'N',
        Rarity: 8,
        Size: '8-10',
        Qualities: 'Breach 3, Ion, Slow-Firing 2',
        Source: 'SWA/F02',
      },
      selected: true,
      Index: 4,
      cooldown: 4,
    },
    {
      count: 15,
      linked: 1,
      mount: 'turret',
      position: 'port',
      type: 'Ion Cannon (Battleship)',
      stats: {
        Name: 'Ion Cannon (Battleship)',
        Skill: 'Gunnery',
        Range: 'Long',
        Dam: '9',
        Crit: '4',
        Price: '10,000',
        Restricted: 'N',
        Rarity: 8,
        Size: '8-10',
        Qualities: 'Breach 3, Ion, Slow-Firing 2',
        Source: 'SWA/F02',
      },
      selected: true,
      Index: 5,
      cooldown: 4,
    },
    {
      count: 15,
      linked: 1,
      mount: 'turret',
      position: 'starboard',
      type: 'Ion Cannon (Battleship)',
      stats: {
        Name: 'Ion Cannon (Battleship)',
        Skill: 'Gunnery',
        Range: 'Long',
        Dam: '9',
        Crit: '4',
        Price: '10,000',
        Restricted: 'N',
        Rarity: 8,
        Size: '8-10',
        Qualities: 'Breach 3, Ion, Slow-Firing 2',
        Source: 'SWA/F02',
      },
      selected: true,
      Index: 6,
      cooldown: 4,
    },
    {
      count: 10,
      linked: 0,
      mount: 'hull',
      position: 'hull',
      type: 'Tractor Beam (Heavy)',
      stats: {
        Name: 'Tractor Beam (Heavy)',
        Skill: 'Gunnery',
        Range: 'Short',
        Dam: '—',
        Crit: '—',
        Price: '10,000',
        Restricted: 'N',
        Rarity: 6,
        Size: '5-10',
        Qualities: 'Tractor 6',
        Source: 'All Core',
      },
    },
  ],
  Source: 'SWA02',
  curr_HT: 86,
  curr_SS: 55,
  crits: [
    {
      difficulty: 2,
      name: 'Shields Failing ',
      desc:
        'Decrease defense in all defense zones by 1 until repaired. If ship or vehicle has no defense, suffer 2 system strain.',
    },
  ],
  captain: 'Rear Admiral M@-33',
  id: 80820624,
  Name: 'Praetor',
  acted: true,
};
const ascension = {
  hullType: 'Heavy Cruiser',
  Class: 'Kantoban',
  Silhouette: 6,
  Speed: 3,
  Handling: -1,
  defFore: 1,
  defPort: 5,
  defStarboard: 1,
  defAft: 1,
  Armor: 6,
  HT: 75,
  SS: 60,
  Manufacturer: 'MandalMotors',
  Massive: 0,
  Hyperdrive: 'Primary: Class 2, Backup: Class 10',
  Navicomputer: true,
  sensorRange: 'Long',
  image: 'kandoben.jpg',
  shipsComplement: '800 crew and troop support',
  dockingBay:
    '54 starfighters, six assault speeders, four troop speeders, two command speeders, and two shuttles.',
  encumbranceCapacity: '4,000',
  passengerCapacity: '250',
  Consumables: 'Two years',
  Cost: '10,000,000',
  Restricted: true,
  Rarity: 9,
  HP: 0,
  Weapons: [
    {
      count: 2,
      linked: 3,
      mount: 'turret',
      position: 'dorsal',
      type: 'Turbolaser (Heavy)',
      stats: {
        Name: 'Turbolaser (Heavy)',
        Skill: 'Gunnery',
        Range: 'Long',
        Dam: '11',
        Crit: '3',
        Price: '20,000',
        Restricted: 'Y',
        Rarity: 8,
        Size: '6-10',
        Qualities: 'Breach 4, Slow-Firing 2',
        Source: 'All Core',
      },
      selected: true,
      Index: 0,
      cooldown: 4,
    },
    {
      count: 2,
      linked: 0,
      mount: 'turret',
      position: 'ventral',
      type: 'Ion Cannon (Heavy)',
      stats: {
        Name: 'Ion Cannon (Heavy)',
        Skill: 'Gunnery',
        Range: 'Medium',
        Dam: '7',
        Crit: '4',
        Price: '7,500',
        Restricted: 'N',
        Rarity: 7,
        Size: '6-10',
        Qualities: 'Slow Firing 1, Ion',
        Source: 'All Core',
      },
      selected: false,
      Index: 1,
    },
    {
      count: 2,
      linked: 3,
      mount: 'starboard',
      position: 'starboard',
      type: 'Turbolaser (Medium)',
      stats: {
        Name: 'Turbolaser (Medium)',
        Skill: 'Gunnery',
        Range: 'Long',
        Dam: '10',
        Crit: '3',
        Price: '15,000',
        Restricted: 'Y',
        Rarity: 7,
        Size: '6-10',
        Qualities: 'Breach 3, Slow-Firing 1',
        Source: 'All Core',
      },
    },
    {
      count: 2,
      linked: 3,
      mount: 'port',
      position: 'port',
      type: 'Turbolaser (Medium)',
      stats: {
        Name: 'Turbolaser (Medium)',
        Skill: 'Gunnery',
        Range: 'Long',
        Dam: '10',
        Crit: '3',
        Price: '15,000',
        Restricted: 'Y',
        Rarity: 7,
        Size: '6-10',
        Qualities: 'Breach 3, Slow-Firing 1',
        Source: 'All Core',
      },
      selected: false,
      Index: 3,
    },
    {
      count: 1,
      linked: 1,
      mount: 'forward',
      position: 'forward',
      type: 'Proton Torpedo Launcher',
      stats: {
        Name: 'Proton Torpedo Launcher',
        Skill: 'Gunnery',
        Range: 'Short',
        Dam: '8',
        Crit: '2',
        Price: '9,000',
        Restricted: 'Y',
        Rarity: 7,
        Size: '3-10',
        Qualities: 'Blast 6, Breach 6, Guided 2, Limited Ammo 3, Slow-Firing 1',
        Source: 'All Core',
      },
    },
    {
      count: 1,
      linked: 0,
      mount: 'forward',
      position: 'forward',
      type: 'Tractor Beam (Heavy)',
      stats: {
        Name: 'Tractor Beam (Heavy)',
        Skill: 'Gunnery',
        Range: 'Short',
        Dam: '—',
        Crit: '—',
        Price: '10,000',
        Restricted: 'N',
        Rarity: 6,
        Size: '5-10',
        Qualities: 'Tractor 6',
        Source: 'All Core',
      },
    },
  ],
  id: 85643018,
  curr_HT: 51,
  curr_SS: 60,
  crits: [],
  captain: 'Commander Kos',
  Name: 'Ascension',
  acted: true,
};
const tarsas = {
  hullType: 'Carrier',
  Class: 'Ton-Falk',
  Silhouette: 7,
  Speed: 2,
  Handling: -3,
  defFore: 1,
  defPort: 5,
  defStarboard: 1,
  defAft: 1,
  Armor: 4,
  HT: 80,
  SS: 60,
  Manufacturer: 'Kuat Drive Yards',
  Massive: 1,
  Hyperdrive: 'Primary: Class 2, Backup: Class 12',
  Navicomputer: 'Yes',
  sensorRange: 'Long',
  image: 'tonfalk.jpg',
  shipsComplement: '4,000 officers, pilots, and enlisted crew',
  dockingBay: '72 starfighters',
  encumbranceCapacity: '9,000',
  passengerCapacity: '800 troops',
  Consumables: 'One year',
  Cost: '3,500,000',
  Restricted: 'Y',
  Rarity: 7,
  HP: 3,
  Weapons: [
    {
      count: 5,
      linked: 1,
      mount: 'turret',
      position: 'port',
      type: 'Laser Cannon (Light)',
      stats: {
        Name: 'Laser Cannon (Light)',
        Skill: 'Gunnery',
        Range: 'Close',
        Dam: '5',
        Crit: '3',
        Price: '5,500',
        Restricted: 'N',
        Rarity: 4,
        Size: '3-10',
        Qualities: '',
        Source: 'All Core',
      },
    },
    {
      count: 5,
      linked: 1,
      mount: 'turret',
      position: 'starboard',
      type: 'Laser Cannon (Light)',
      stats: {
        Name: 'Laser Cannon (Light)',
        Skill: 'Gunnery',
        Range: 'Close',
        Dam: '5',
        Crit: '3',
        Price: '5,500',
        Restricted: 'N',
        Rarity: 4,
        Size: '3-10',
        Qualities: '',
        Source: 'All Core',
      },
    },
    {
      count: 1,
      linked: 1,
      mod: {
        Qualities: {
          Guided: '4',
        },
      },
      mount: 'forward',
      position: 'forward',
      type: 'Concussion Missile Launcher',
      stats: {
        Name: 'Concussion Missile Launcher',
        Skill: 'Gunnery',
        Range: 'Short',
        Dam: '6',
        Crit: '3',
        Price: '7,500',
        Restricted: 'N',
        Rarity: 5,
        Size: '3-10',
        Qualities: 'Blast 4, Breach 4, Guided 4, Limited Ammo 3, Slow-Firing 1',
        Source: 'All Core',
      },
    },
    {
      count: 4,
      linked: 0,
      mount: 'hull',
      position: 'hull',
      type: 'Tractor Beam (Medium)',
      stats: {
        Name: 'Tractor Beam (Medium)',
        Skill: 'Gunnery',
        Range: 'Short ',
        Dam: '—',
        Crit: '—',
        Price: '8,000',
        Restricted: 'N',
        Rarity: 5,
        Size: '5-10',
        Qualities: 'Tractor 4',
        Source: 'All Core',
      },
    },
  ],
  Source: 'SWA25',
  curr_HT: 62,
  curr_SS: 60,
  crits: [],
  captain: 'Commander Val Mariell',
  id: 44438667,
  Name: "Tarsa's Obedience",
  acted: false,
};
