
    
    
   
    {
      "hullType": "Cruiser",
      "Class": "Interdictor",
      "Silhouette": 7,
      "Speed": 2,
      "Handling": -2,
      "defFore": 3,
      "defPort": 3,
      "defStarboard": 3,
      "defAft": 2,
      "Armor": 5,
      "HT": 75,
      "SS": 65,
      "Manufacturer": "Sienar Fleet System",
      "Hyperdrive": "Primary: Class 2, Backup: Class 12",
      "Navicomputer": "Yes",
      "sensorRange": "Long",
      "shipsComplement": "2807 officers, pilots, and enlisted crew",
      "dockingBay": "N/A",
      "encumbranceCapacity": "6,500",
      "passengerCapacity": "80 troops",
      "Consumables": "Sixteen months",
      "Cost": "15,400,000",
      "Restricted": "Y",
      "Rarity": 8,
      "HP": 0,
      "Weapons": "Five dorsal, five ventral, four port, four starboard, and two aft turret-mounted quad laser cannons",
      "Source": "SWE12"
    },
    {
      "hullType": "Frigate",
      "Class": "Munificent",
      "Silhouette": 7,
      "Speed": 2,
      "Handling": 0,
      "defFore": 3,
      "defPort": 2,
      "defStarboard": 2,
      "defAft": 2,
      "Armor": 5,
      "HT": 60,
      "SS": 55,
      "Manufacturer": "Hoersch-liessel Drive, inc.",
      "Hyperdrive": "Primary: Class 1, Backup: Class 10",
      "Navicomputer": "Yes",
      "sensorRange": "Long",
      "shipsComplement": "1,100 officers, pilots, and enlisted crew.",
      "dockingBay": "Twelve to thirty-six starfighters, depending on conﬁguration",
      "encumbranceCapacity": "10,000",
      "passengerCapacity": "850",
      "Consumables": "Two years",
      "Cost": "12,300,000",
      "Restricted": "N",
      "Rarity": 9,
      "HP": 1,
      "Weapons": "Two forward-mounted heavy turbolasers. Two forward--rneunted long-barrelled ion cannons. Thirteen port and thirteen starboard twin light turbolasers. Ten port and ten starboard turret-mounted light turbolasers. Four port and four starboard medium flak cannons. Ten dorsal, ten ventral, ten starboard, and ten port turret-mounted retractable light laser cannons ",
      "Source": "SWA36"
    },
    {
      "hullType": "Cruiser",
      "Class": "Vindicator",
      "Silhouette": 7,
      "Speed": 3,
      "Handling": -1,
      "defFore": 3,
      "defPort": 2,
      "defStarboard": 2,
      "defAft": 2,
      "Armor": 6,
      "HT": 85,
      "SS": 55,
      "Manufacturer": "Sienar Fleet Systems",
      "Hyperdrive": "Primary: Class 2, Backup: Class 12",
      "Navicomputer": "Yes",
      "sensorRange": "Long",
      "shipsComplement": "2,551 officers, pilots, and enlisted crew.",
      "dockingBay": "24 starfighters",
      "encumbranceCapacity": "7,500",
      "passengerCapacity": "400 troops",
      "Consumables": "Sixteen months",
      "Cost": "10,400,000",
      "Restricted": "Y",
      "Rarity": 8,
      "HP": 0,
      "Weapons": "Five dorsal, five port, and five starboard medium turbolasers, Five port and five starboard quad light turbolaser batteries, Six forward, eight port, eight starboard, and eight aft point defense laser cannons, One forward, one port, and one starboard heavy tractor beam emitters",
      "Source": "SWA02"
    },
    {
      "hullType": "Transport",
      "Class": "Star Galleon",
      "Silhouette": 6,
      "Speed": 1,
      "Handling": -2,
      "defFore": 2,
      "defPort": 2,
      "defStarboard": 2,
      "defAft": 2,
      "Armor": 5,
      "HT": 85,
      "SS": 18,
      "Manufacturer": "Kuat Drive Yards",
      "Hyperdrive": "Primary: Class 2, Backup: Class 15",
      "Navicomputer": "Yes",
      "sensorRange": "Medium",
      "shipsComplement": "One-hundred fifty officers and enlisted crew",
      "dockingBay": "N/A",
      "encumbranceCapacity": "10,000",
      "passengerCapacity": "300",
      "Consumables": "Six months",
      "Cost": "1,500,000",
      "Restricted": "Y",
      "Rarity": 7,
      "HP": 2,
      "Weapons": "Five Port and Five Starboard Mounted Retractable Medium Turbolasers, Forward Concussion Missile Launcher",
      "Source": "SWE02"
    },
    {
      "hullType": "Destroyer",
      "Class": "Adz",
      "Silhouette": 5,
      "Speed": 2,
      "Handling": -2,
      "defFore": 2,
      "defPort": 2,
      "defStarboard": 2,
      "defAft": 1,
      "Armor": 6,
      "HT": 50,
      "SS": 35,
      "Manufacturer": "Kuat Drive Yards",
      "Hyperdrive": "Primary: Class 2, Backup: Class 12",
      "Navicomputer": "Yes",
      "sensorRange": "Extreme",
      "shipsComplement": "30 officers, pilots, and crew",
      "dockingBay": "6 starfighters",
      "encumbranceCapacity": "350",
      "passengerCapacity": "8",
      "Consumables": "Three months",
      "Cost": "4,450,000",
      "Restricted": "Y",
      "Rarity": 7,
      "HP": 1,
      "Weapons": "Two forward and one aft dorsal turret-mounted quad laser cannons, Two port and two startboard turret-mounted light ion cannons",
      "Source": "SWF02"
    },
    {
      "hullType": "Corvette",
      "Class": "Raider I",
      "Silhouette": 5,
      "Speed": 4,
      "Handling": -1,
      "defFore": 2,
      "defPort": 2,
      "defStarboard": 2,
      "defAft": 2,
      "Armor": 5,
      "HT": 45,
      "SS": 25,
      "Manufacturer": "Kuat Drive Yards",
      "Hyperdrive": "Primary: Class 2, Backup: Class 15",
      "Navicomputer": "Yes",
      "sensorRange": "Long",
      "shipsComplement": "15 officers, and 77 enlisted crew",
      "dockingBay": "N/A",
      "encumbranceCapacity": "300",
      "passengerCapacity": "30",
      "Consumables": "Three Months",
      "Cost": "3,000,000",
      "Restricted": "Y",
      "Rarity": 7,
      "HP": 2,
      "Weapons": "Chin-mounted twin light turbolasers. Three port and three starboard retractable turretmounted twin heavy laser cannons. Chin-mounted ion cannon.",
      "Source": "SWA41"
    }