
    {
      "hullType": "Frigate",
      "Class": "IR-3F",
      "Silhouette": 5,
      "Speed": 4,
      "Handling": -1,
      "defFore": 2,
      "defPort": 2,
      "defStarboard": 2,
      "defAft": 2,
      "Armor": 3,
      "HT": 40,
      "SS": 35,
      "Manufacturer": "Republic Sienar Systems",
      "Hyperdrive": "None",
      "Navicomputer": "None",
      "sensorRange": "Extreme",
      "shipsComplement": "20 officers, and crew",
      "dockingBay": "N/A",
      "encumbranceCapacity": "1,800",
      "passengerCapacity": "10",
      "Consumables": "One month",
      "Cost": "1,000,000",
      "Restricted": "N",
      "Rarity": 6,
      "HP": 2,
      "Weapons": "One Ventral Turret Mounted Twin Light Trubolaser battery, One Dorsal twin-mounted twin light turbolaser battery, One port and one starboard turret-mounted twin medium laser cannon",
      "Source": "SWF02"
    },
    {
      "hullType": "Transport",
      "Class": "Action VI",
      "Silhouette": 5,
      "Speed": 2,
      "Handling": -3,
      "defFore": 2,
      "defPort": 1,
      "defStarboard": 1,
      "defAft": 1,
      "Armor": 2,
      "HT": 40,
      "SS": 20,
      "Manufacturer": "Corellian Engineering Corporation",
      "Hyperdrive": "Primary: Class 3, Backup: Class 20",
      "Navicomputer": "Yes",
      "sensorRange": "Medium",
      "shipsComplement": "Twenty Crew",
      "dockingBay": "N/A",
      "encumbranceCapacity": "10,000",
      "passengerCapacity": "5",
      "Consumables": "Three months",
      "Cost": "200,000",
      "Restricted": "N",
      "Rarity": 5,
      "HP": 4,
      "Weapons": "None",
      "Source": "SWE02"
    },
    {
      "hullType": "Light Cruiser",
      "Class": "C-ROC Gozanti-class",
      "Silhouette": 5,
      "Speed": 3,
      "Handling": -3,
      "defFore": 3,
      "defPort": 2,
      "defStarboard": 2,
      "defAft": 1,
      "Armor": 5,
      "HT": 55,
      "SS": 40,
      "Manufacturer": "Corellian Engineering Corporation",
      "Hyperdrive": "Primary: Class 3, Backup: Class 12",
      "Navicomputer": "Yes",
      "sensorRange": "Medium",
      "shipsComplement": "One pilot, one co-pilot, one engineer, one comms/sensors operator, two loadmasters, six gunners.",
      "dockingBay": "N/A",
      "encumbranceCapacity": "1,800",
      "passengerCapacity": "20",
      "Consumables": "Two months",
      "Cost": "190,000",
      "Restricted": "N",
      "Rarity": 8,
      "HP": 6,
      "Weapons": "One dorsal and one ventral retractable turret-mounted quad laser cannon, Two port and two starboard retractable twin heavy laser cannons, Forward-mounted proton torpedo launcher",
      "Source": "SWE16"
    },
    {
      "hullType": "Dreadnought",
      "Class": "Assertor",
      "Silhouette": 9,
      "Speed": 2,
      "Handling": -4,
      "defFore": 4,
      "defPort": 3,
      "defStarboard": 3,
      "defAft": 2,
      "Armor": 13,
      "HT": 205,
      "SS": 105,
      "Manufacturer": "Kuat Drive Yards",
      "Hyperdrive": "Primary: Class 2, Backup: Class 12",
      "Navicomputer": "Yes",
      "sensorRange": "Long",
      "shipsComplement": "125,000 ofﬁcers, pilots, and enlisted crew.",
      "dockingBay": "120 starfighters",
      "encumbranceCapacity": "145,000",
      "passengerCapacity": "20,000",
      "Consumables": "Three years",
      "Cost": "1,100,000,000",
      "Restricted": "Y",
      "Rarity": 10,
      "HP": 2,
      "Weapons": "Twenty port and twenty starboard quad heavy turbolaser batteries. Fifteen port and ﬁfteen starboard quad battleship ion cannon batteries. Ten dorsal twin heavy turbolasers. Ten forward. ten port. and ten starboard quad light turbolaser batteries",
      "Source": "SWA36"
    },
    {
      "hullType": "Star Destroyer",
      "Class": "Imperial I",
      "Silhouette": 8,
      "Speed": 2,
      "Handling": -3,
      "defFore": 3,
      "defPort": 3,
      "defStarboard": 3,
      "defAft": 2,
      "Armor": 10,
      "HT": 145,
      "SS": 60,
      "Manufacturer": "Kuat Drive Yards",
      "Hyperdrive": "Primary: Class 2, Backup: Class 8",
      "Navicomputer": "Yes",
      "sensorRange": "Long",
      "shipsComplement": "37,085 officers, pilots, and enlisted crew",
      "dockingBay": "72 starfighters",
      "encumbranceCapacity": "15,000",
      "passengerCapacity": "9,700",
      "Consumables": "Two years",
      "Cost": "150,000,000",
      "Restricted": "Y",
      "Rarity": 7,
      "HP": 2,
      "Weapons": "Ten port and ten starboard heavy turbolaser batteries, Ten dorsal heavy turbolaser batteries, Ten port, ten starboard, and ten forward light turbolasers, Ten port and ten starboard battleship ion cannon turrets, Ten ventral battleship ion cannon batteries, Fifteen port and fifteen starboard medium ion cannons, Ten heavy tractor beam emitters",
      "Source": "SWA02"
    },
    {
      "hullType": "Cruiser",
      "Class": "Secutor",
      "Silhouette": 8,
      "Speed": 2,
      "Handling": -4,
      "defFore": 3,
      "defPort": 3,
      "defStarboard": 3,
      "defAft": 2,
      "Armor": 8,
      "HT": 130,
      "SS": 55,
      "Manufacturer": "Kuat Drive Yards",
      "Hyperdrive": "Primary: Class 2, Backup: Class 14",
      "Navicomputer": "Yes",
      "sensorRange": "Long",
      "shipsComplement": "40,000 officers, pilots, and enlisted crew.",
      "dockingBay": "144 starfighters",
      "encumbranceCapacity": "28,000",
      "passengerCapacity": "14000 troops",
      "Consumables": "Two years",
      "Cost": "200,000,000",
      "Restricted": "Y",
      "Rarity": 7,
      "HP": 2,
      "Weapons": "Five port and five starboard heavy turbolaser batteries, Five dorsal heavy turbolaser batteries, Five port, five starboard, and five forward light turbolasers, Five port and five starboard battleship ion cannon turrets, Five ventral battleship ion cannon batteries, Twelve hull-mounted heavy tractor beam emitters",
      "Source": "SWA25"
    },
    {
      "hullType": "Star Destroyer",
      "Class": "Victory II",
      "Silhouette": 8,
      "Speed": 1,
      "Handling": -3,
      "defFore": 2,
      "defPort": 2,
      "defStarboard": 2,
      "defAft": 2,
      "Armor": 9,
      "HT": 120,
      "SS": 50,
      "Manufacturer": "Kuat Drive Yards",
      "Hyperdrive": "Primary: Class 1, Backup: Class 15",
      "Navicomputer": "Yes",
      "sensorRange": "Long",
      "shipsComplement": "6,107 officers, pilots, and enlisted crew",
      "dockingBay": "24 starfighters",
      "encumbranceCapacity": "6,500",
      "passengerCapacity": "1,600",
      "Consumables": "One year",
      "Cost": "50,000,000",
      "Restricted": "Y",
      "Rarity": 6,
      "HP": 4,
      "Weapons": "Five port and hve starboard light quad turbolaser batteries, Ten forward-mounted twin medium turbolasers, Ten dorsal twin medium turbolasers, Twenty assault concussion missile launchers, Ten hull-mounted heavy tractor beams",
      "Source": "SWA/F02"
    },
    {
      "hullType": "Star Destroyer",
      "Class": "Gladiator",
      "Silhouette": 7,
      "Speed": 3,
      "Handling": -2,
      "defFore": 3,
      "defPort": 2,
      "defStarboard": 2,
      "defAft": 1,
      "Armor": 7,
      "HT": 90,
      "SS": 35,
      "Manufacturer": "Kuat Drive Yards",
      "Hyperdrive": "Primary: Class 1, Backup: Class 8",
      "Navicomputer": "Yes",
      "sensorRange": "Long",
      "shipsComplement": "1,255 officers, pilots, and enlisted crew",
      "dockingBay": "24 starfighters",
      "encumbranceCapacity": "5,000",
      "passengerCapacity": "1,200",
      "Consumables": "Two years",
      "Cost": "34,000,000",
      "Restricted": "Y",
      "Rarity": 7,
      "HP": 2,
      "Weapons": "Twelve dual turret-mounted light turbo lasers. Three port, three starboard, and four aft turret-mounted medium laser cannons. Ten assault concussion missile launchers. Four forward, two port, and two starboard medium tractor beams",
      "Source": "SWA41"
    },
    {
      "hullType": "Cruiser",
      "Class": "Interdictor",
      "Silhouette": 7,
      "Speed": 2,
      "Handling": -2,
      "defFore": 3,
      "defPort": 3,
      "defStarboard": 3,
      "defAft": 2,
      "Armor": 5,
      "HT": 75,
      "SS": 65,
      "Manufacturer": "Sienar Fleet System",
      "Hyperdrive": "Primary: Class 2, Backup: Class 12",
      "Navicomputer": "Yes",
      "sensorRange": "Long",
      "shipsComplement": "2807 officers, pilots, and enlisted crew",
      "dockingBay": "N/A",
      "encumbranceCapacity": "6,500",
      "passengerCapacity": "80 troops",
      "Consumables": "Sixteen months",
      "Cost": "15,400,000",
      "Restricted": "Y",
      "Rarity": 8,
      "HP": 0,
      "Weapons": "Five dorsal, five ventral, four port, four starboard, and two aft turret-mounted quad laser cannons",
      "Source": "SWE12"
    },
    {
      "hullType": "Frigate",
      "Class": "Munificent",
      "Silhouette": 7,
      "Speed": 2,
      "Handling": 0,
      "defFore": 3,
      "defPort": 2,
      "defStarboard": 2,
      "defAft": 2,
      "Armor": 5,
      "HT": 60,
      "SS": 55,
      "Manufacturer": "Hoersch-liessel Drive, inc.",
      "Hyperdrive": "Primary: Class 1, Backup: Class 10",
      "Navicomputer": "Yes",
      "sensorRange": "Long",
      "shipsComplement": "1,100 officers, pilots, and enlisted crew.",
      "dockingBay": "Twelve to thirty-six starfighters, depending on conﬁguration",
      "encumbranceCapacity": "10,000",
      "passengerCapacity": "850",
      "Consumables": "Two years",
      "Cost": "12,300,000",
      "Restricted": "N",
      "Rarity": 9,
      "HP": 1,
      "Weapons": "Two forward-mounted heavy turbolasers. Two forward--rneunted long-barrelled ion cannons. Thirteen port and thirteen starboard twin light turbolasers. Ten port and ten starboard turret-mounted light turbolasers. Four port and four starboard medium flak cannons. Ten dorsal, ten ventral, ten starboard, and ten port turret-mounted retractable light laser cannons ",
      "Source": "SWA36"
    },
    {
      "hullType": "Cruiser",
      "Class": "Vindicator",
      "Silhouette": 7,
      "Speed": 3,
      "Handling": -1,
      "defFore": 3,
      "defPort": 2,
      "defStarboard": 2,
      "defAft": 2,
      "Armor": 6,
      "HT": 85,
      "SS": 55,
      "Manufacturer": "Sienar Fleet Systems",
      "Hyperdrive": "Primary: Class 2, Backup: Class 12",
      "Navicomputer": "Yes",
      "sensorRange": "Long",
      "shipsComplement": "2,551 officers, pilots, and enlisted crew.",
      "dockingBay": "24 starfighters",
      "encumbranceCapacity": "7,500",
      "passengerCapacity": "400 troops",
      "Consumables": "Sixteen months",
      "Cost": "10,400,000",
      "Restricted": "Y",
      "Rarity": 8,
      "HP": 0,
      "Weapons": "Five dorsal, five port, and five starboard medium turbolasers, Five port and five starboard quad light turbolaser batteries, Six forward, eight port, eight starboard, and eight aft point defense laser cannons, One forward, one port, and one starboard heavy tractor beam emitters",
      "Source": "SWA02"
    },
    {
      "hullType": "Transport",
      "Class": "Star Galleon",
      "Silhouette": 6,
      "Speed": 1,
      "Handling": -2,
      "defFore": 2,
      "defPort": 2,
      "defStarboard": 2,
      "defAft": 2,
      "Armor": 5,
      "HT": 85,
      "SS": 18,
      "Manufacturer": "Kuat Drive Yards",
      "Hyperdrive": "Primary: Class 2, Backup: Class 15",
      "Navicomputer": "Yes",
      "sensorRange": "Medium",
      "shipsComplement": "One-hundred fifty officers and enlisted crew",
      "dockingBay": "N/A",
      "encumbranceCapacity": "10,000",
      "passengerCapacity": "300",
      "Consumables": "Six months",
      "Cost": "1,500,000",
      "Restricted": "Y",
      "Rarity": 7,
      "HP": 2,
      "Weapons": "Five Port and Five Starboard Mounted Retractable Medium Turbolasers, Forward Concussion Missile Launcher",
      "Source": "SWE02"
    },
    {
      "hullType": "Destroyer",
      "Class": "Adz",
      "Silhouette": 5,
      "Speed": 2,
      "Handling": -2,
      "defFore": 2,
      "defPort": 2,
      "defStarboard": 2,
      "defAft": 1,
      "Armor": 6,
      "HT": 50,
      "SS": 35,
      "Manufacturer": "Kuat Drive Yards",
      "Hyperdrive": "Primary: Class 2, Backup: Class 12",
      "Navicomputer": "Yes",
      "sensorRange": "Extreme",
      "shipsComplement": "30 officers, pilots, and crew",
      "dockingBay": "6 starfighters",
      "encumbranceCapacity": "350",
      "passengerCapacity": "8",
      "Consumables": "Three months",
      "Cost": "4,450,000",
      "Restricted": "Y",
      "Rarity": 7,
      "HP": 1,
      "Weapons": "Two forward and one aft dorsal turret-mounted quad laser cannons, Two port and two startboard turret-mounted light ion cannons",
      "Source": "SWF02"
    },
    {
      "hullType": "Corvette",
      "Class": "Raider I",
      "Silhouette": 5,
      "Speed": 4,
      "Handling": -1,
      "defFore": 2,
      "defPort": 2,
      "defStarboard": 2,
      "defAft": 2,
      "Armor": 5,
      "HT": 45,
      "SS": 25,
      "Manufacturer": "Kuat Drive Yards",
      "Hyperdrive": "Primary: Class 2, Backup: Class 15",
      "Navicomputer": "Yes",
      "sensorRange": "Long",
      "shipsComplement": "15 officers, and 77 enlisted crew",
      "dockingBay": "N/A",
      "encumbranceCapacity": "300",
      "passengerCapacity": "30",
      "Consumables": "Three Months",
      "Cost": "3,000,000",
      "Restricted": "Y",
      "Rarity": 7,
      "HP": 2,
      "Weapons": "Chin-mounted twin light turbolasers. Three port and three starboard retractable turretmounted twin heavy laser cannons. Chin-mounted ion cannon.",
      "Source": "SWA41"
    }