const shipForm = [
  {
    data: 'hullType',
    required: true,
    style: 'half',
    title: 'Hull Type',
    type: 'text',
  },
  {
    data: 'Class',
    required: true,
    style: 'half',
    title: 'Class',
    type: 'text',
  },
  {
    data: 'Silhouette',
    required: true,
    style: 'eighth',
    title: 'Silhouette',
    type: 'number',
  },
  {
    data: 'Speed',
    required: true,
    style: 'eighth',
    title: 'Speed',
    type: 'number',
  },
  {
    data: 'Handling',
    required: true,
    style: 'eighth',
    title: 'Handling',
    type: 'number',
  },
  {
    data: 'defFore',
    required: true,
    style: 'quarter',
    title: 'Defense Fore',
    type: 'number',
  },
  {
    data: 'defPort',
    required: true,
    style: 'quarter',
    title: 'Defense Port',
    type: 'number',
  },
  {
    data: 'defStarboard',
    required: true,
    style: 'quarter',
    title: 'Defense Starboard',
    type: 'number',
  },
  {
    data: 'defAft',
    required: true,
    style: 'quarter',
    title: 'Defense Aft',
    type: 'number',
  },
  {
    data: 'Armor',
    required: true,
    style: 'eighth',
    title: 'Armor',
    type: 'number',
  },
  {
    data: 'HT',
    required: true,
    style: 'quarter',
    title: 'Hull Trauma',
    type: 'number',
  },
  {
    data: 'SS',
    required: true,
    style: 'quarter',
    title: 'System Strain',
    type: 'number',
  },
  {
    data: 'Manufacturer',
    required: false,
    style: 'half',
    title: 'Manufacturer',
    type: 'text',
  },
  {
    data: 'Massive',
    required: false,
    style: 'quarter',
    title: 'Massive Quality',
    type: 'number',
  },
  {
    data: 'Hyperdrive',
    required: false,
    style: 'half',
    title: 'Hyperdrive',
    type: 'text',
  },
  {
    data: 'Navicomputer',
    options: {
      true: 'Yes',
      false: 'No',
    },
    required: true,
    style: 'quarter',
    title: 'Navicomputer',
    type: 'toggle',
  },
  {
    data: 'sensorRange',
    required: true,
    style: 'quarter',
    title: 'Sensor Range',
    type: 'text',
  },
  {
    data: 'image',
    required: false,
    style: 'quarter',
    title: 'Image Filename',
    type: 'text',
  },
  {
    data: 'shipsComplement',
    required: true,
    style: 'full',
    title: "Ship's Compliment",
    type: 'text',
  },
  {
    data: 'dockingBay',
    required: false,
    style: 'half',
    title: 'Docking Bay',
    type: 'text',
  },
  {
    data: 'encumbranceCapacity',
    required: true,
    style: 'quarter',
    title: 'Encumbrance Capacity',
    type: 'text',
  },
  {
    data: 'passengerCapacity',
    required: true,
    style: 'quarter',
    title: 'Passenger Capacity',
    type: 'text',
  },
  {
    data: 'Consumables',
    required: true,
    style: 'quarter',
    title: 'Consumables',
    type: 'text',
  },
  {
    data: 'Cost',
    required: true,
    style: 'quarter',
    title: 'Cost',
    type: 'text',
  },
  {
    data: 'Restricted',
    options: {
      true: 'Y',
      false: 'N',
    },
    required: true,
    style: 'eighth',
    title: 'Restricted',
    type: 'toggle',
  },
  {
    data: 'Rarity',
    required: true,
    style: 'eighth',
    title: 'Rarity',
    type: 'number',
  },
  {
    data: 'HP',
    required: true,
    style: 'eighth',
    title: 'Hardpoints',
    type: 'number',
  },
];
export default shipForm;
