const weapons = [
  {
    Name: 'A x-108 Surface Defense Blaster Cannon',
    Skill: 'Ranged (Heavy)',
    Range: 'Medium',
    Dam: '12',
    Crit: '3',
    Price: '2,000',
    Restricted: 'N',
    Rarity: 6,
    Size: '3-10',
    Qualities: 'Auto-fire, Pierce 2, Personal ',
    Source: 'SWE12',
  },
  {
    Name: 'Auto-Blaster',
    Skill: 'Gunnery',
    Range: 'Close',
    Dam: '3',
    Crit: '5',
    Price: '3,000',
    Restricted: 'N',
    Rarity: 3,
    Size: '2-10',
    Qualities: 'Auto-Fire',
    Source: 'All Core',
  },
  {
    Name: 'Blaster Cannon (Heavy)',
    Skill: 'Gunnery',
    Range: 'Close',
    Dam: '5',
    Crit: '4',
    Price: '5,000',
    Restricted: 'N',
    Rarity: 3,
    Size: '3-10',
    Qualities: '',
    Source: 'All Core',
  },
  {
    Name: 'Blaster Cannon (Light)',
    Skill: 'Gunnery',
    Range: 'Close',
    Dam: '4',
    Crit: '4',
    Price: '4,000',
    Restricted: 'N',
    Rarity: 2,
    Size: '2-10',
    Qualities: '',
    Source: 'All Core',
  },
  {
    Name: 'Concussion Missile ',
    Skill: 'Gunnery',
    Range: 'Short',
    Dam: '6',
    Crit: '3',
    Price: '500',
    Restricted: 'Y',
    Rarity: 5,
    Size: '',
    Qualities: 'Blast 4, Breach 4, Guided 3, Limited Ammo 3, Slow-Firing 1',
    Source: 'All Core',
  },
  {
    Name: 'Mass Driver Missile Launcher',
    Skill: 'Gunnery',
    Range: 'Extreme',
    Dam: '14',
    Crit: '3',
    Price: '500',
    Restricted: 'Y',
    Rarity: 5,
    Size: '',
    Qualities: 'Blast 4, Breach 4, Inaccurate 1, Limited Ammo 10, Slow-Firing 2',
    Source: 'All Core',
  },
  {
    Name: 'Concussion Missile (Assault)',
    Skill: 'Gunnery',
    Range: 'Short',
    Dam: '10',
    Crit: '3',
    Price: '500',
    Restricted: 'Y',
    Rarity: 5,
    Size: '',
    Qualities: 'Blast 10, Breach 10, Inaccurate 4, Slow-Firing 4',
    Source: 'All Core',
  },
  {
    Name: 'Concussion Missile (mini)',
    Skill: 'Gunnery',
    Range: 'Short',
    Dam: '4',
    Crit: '4',
    Price: '400',
    Restricted: 'N',
    Rarity: 5,
    Size: '',
    Qualities: 'Blast 2, Breach 2, Guided 3, Slow-Firing 1',
    Source: 'SWE08',
  },
  {
    Name: 'Concussion Missile Launcher',
    Skill: 'Gunnery',
    Range: 'Short',
    Dam: '6',
    Crit: '3',
    Price: '7,500',
    Restricted: 'N',
    Rarity: 5,
    Size: '3-10',
    Qualities: 'Blast 4, Breach 4, Guided 3, Limited Ammo 3, Slow-Firing 1',
    Source: 'All Core',
  },
  {
    Name: 'Decoy Missile',
    Skill: 'Gunnery',
    Range: 'Short',
    Dam: '-',
    Crit: '-',
    Price: '400',
    Restricted: 'N',
    Rarity: 6,
    Size: '',
    Qualities: 'Slow-Firing 1',
    Source: 'SWE08',
  },
  {
    Name: 'Electromagnetic Harpoon',
    Skill: 'Gunnery',
    Range: 'Close',
    Dam: '—',
    Crit: '—',
    Price: '',
    Restricted: 'N',
    Rarity: null,
    Size: '2-10',
    Qualities: 'Knockdown, Ensnare 5, Limited Ammo 1',
    Source: 'SWE02',
  },
  {
    Name: 'Flak Cannon (Heavy)',
    Skill: 'Gunnery',
    Range: 'Short',
    Dam: '6',
    Crit: '3',
    Price: '10,000',
    Restricted: 'N',
    Rarity: 7,
    Size: '6-10',
    Qualities: 'Blast 5, Slow-Firing 2, Vicious 5',
    Source: 'SWA25',
  },
  {
    Name: 'Flak Cannon (Light)',
    Skill: 'Gunnery',
    Range: 'Close',
    Dam: '5',
    Crit: '3',
    Price: '6,000',
    Restricted: 'N',
    Rarity: 5,
    Size: ' 4-10',
    Qualities: 'Blast 4, Slow-Firing 1, Vicious 3',
    Source: 'SWA25',
  },
  {
    Name: 'Flak Cannon (Medium)',
    Skill: 'Gunnery',
    Range: 'Short',
    Dam: '5',
    Crit: '3',
    Price: '8,000',
    Restricted: 'N',
    Rarity: 6,
    Size: '5-10',
    Qualities: 'Blast 4, Slow-Firing 1, Vicious 4',
    Source: 'SWA25',
  },
  {
    Name: 'Heavy Flak Cannon',
    Skill: 'Gunnery',
    Range: 'Short',
    Dam: '6',
    Crit: '3',
    Price: '10,000',
    Restricted: 'N',
    Rarity: 7,
    Size: '6-10',
    Qualities: 'Blast 5, Slow-Firing 2, Vicious 5',
    Source: 'SWA36',
  },
  {
    Name: 'Ion Cannon (Battleship)',
    Skill: 'Gunnery',
    Range: 'Medium',
    Dam: '9',
    Crit: '4',
    Price: '10,000',
    Restricted: 'N',
    Rarity: 8,
    Size: '8-10',
    Qualities: 'Breach 3, Ion, Slow-Firing 2',
    Source: 'SWA/F02',
  },
  {
    Name: 'Ion Cannon (Heavy)',
    Skill: 'Gunnery',
    Range: 'Medium',
    Dam: '7',
    Crit: '4',
    Price: '7,500',
    Restricted: 'N',
    Rarity: 7,
    Size: '6-10',
    Qualities: 'Slow Firing 1, Ion',
    Source: 'All Core',
  },
  {
    Name: 'Ion Cannon (Light)',
    Skill: 'Gunnery',
    Range: 'Close',
    Dam: '5',
    Crit: '4',
    Price: '5,000',
    Restricted: 'N',
    Rarity: 5,
    Size: '3-10',
    Qualities: 'Ion',
    Source: 'All Core',
  },
  {
    Name: 'Ion Cannon (Medium)',
    Skill: 'Gunnery',
    Range: 'Short',
    Dam: '6',
    Crit: '4',
    Price: '6,000',
    Restricted: 'N',
    Rarity: 6,
    Size: '5-10',
    Qualities: 'Ion',
    Source: 'All Core',
  },
  {
    Name: 'Jammer Missile',
    Skill: 'Gunnery',
    Range: 'Short',
    Dam: '-',
    Crit: '-',
    Price: '300',
    Restricted: 'N',
    Rarity: 6,
    Size: '',
    Qualities: 'Guided 4, Slow-Firing 1',
    Source: 'SWE08',
  },
  {
    Name: 'Jammer Missile (mini)',
    Skill: 'Gunnery',
    Range: 'Close',
    Dam: '-',
    Crit: '-',
    Price: '400',
    Restricted: 'N',
    Rarity: 6,
    Size: '',
    Qualities: 'Guided 4, Slow-Firing 1',
    Source: 'SWE08',
  },
  {
    Name: 'Laser Cannon (Heavy)',
    Skill: 'Gunnery',
    Range: 'Short',
    Dam: '6',
    Crit: '3',
    Price: '7,500',
    Restricted: 'N',
    Rarity: 5,
    Size: '4-10',
    Qualities: '',
    Source: 'All Core',
  },
  {
    Name: 'Laser Cannon (Light)',
    Skill: 'Gunnery',
    Range: 'Close',
    Dam: '5',
    Crit: '3',
    Price: '5,500',
    Restricted: 'N',
    Rarity: 4,
    Size: '3-10',
    Qualities: '',
    Source: 'All Core',
  },
  {
    Name: 'Laser Cannon (Medium)',
    Skill: 'Gunnery',
    Range: 'Close',
    Dam: '6',
    Crit: '3',
    Price: '7,000',
    Restricted: 'N',
    Rarity: 4,
    Size: '3-10',
    Qualities: '',
    Source: 'All Core',
  },
  {
    Name: 'Light Flak Cannon',
    Skill: 'Gunnery',
    Range: 'Close',
    Dam: '5',
    Crit: '3',
    Price: '6,000',
    Restricted: 'N',
    Rarity: 5,
    Size: '4-10',
    Qualities: 'Blast 4, Slow-Firing 1, Vicious 3',
    Source: 'SWA36',
  },
  {
    Name: 'Medium Flak Cannon',
    Skill: 'Gunnery',
    Range: 'Short',
    Dam: '5',
    Crit: '3',
    Price: '8,000',
    Restricted: 'N',
    Rarity: 6,
    Size: '5-10',
    Qualities: 'Blast 4, Slow-Firing 1, Vicious 4',
    Source: 'SWA36',
  },
  {
    Name: 'Proton Torpedo',
    Skill: 'Gunnery',
    Range: 'Short',
    Dam: '8',
    Crit: '2',
    Price: '750',
    Restricted: 'Y',
    Rarity: 7,
    Size: '',
    Qualities: 'Blast 6, Breach 6, Guided 2, Limited Ammo 3, Slow-Firing 1',
    Source: 'All Core',
  },
  {
    Name: 'Proton Torpedo Launcher',
    Skill: 'Gunnery',
    Range: 'Short',
    Dam: '8',
    Crit: '2',
    Price: '9,000',
    Restricted: 'Y',
    Rarity: 7,
    Size: '3-10',
    Qualities: 'Blast 6, Breach 6, Guided 2, Limited Ammo 3, Slow-Firing 1',
    Source: 'All Core',
  },
  {
    Name: 'Quad Laser Cannon',
    Skill: 'Gunnery',
    Range: 'Close',
    Dam: '5',
    Crit: '3',
    Price: '8,000',
    Restricted: 'N',
    Rarity: 6,
    Size: '4-10',
    Qualities: 'Accurate, Linked 3',
    Source: 'All Core',
  },
  {
    Name: 'Tractor Beam (Heavy)',
    Skill: 'Gunnery',
    Range: 'Short',
    Dam: '—',
    Crit: '—',
    Price: '10,000',
    Restricted: 'N',
    Rarity: 6,
    Size: '5-10',
    Qualities: 'Tractor 6',
    Source: 'All Core',
  },
  {
    Name: 'Tractor Beam (Light)',
    Skill: 'Gunnery',
    Range: 'Close',
    Dam: '—',
    Crit: '—',
    Price: '6,000',
    Restricted: 'N',
    Rarity: 4,
    Size: '4-10',
    Qualities: 'Tractor 2',
    Source: 'All Core',
  },
  {
    Name: 'Tractor Beam (Medium)',
    Skill: 'Gunnery',
    Range: 'Short ',
    Dam: '—',
    Crit: '—',
    Price: '8,000',
    Restricted: 'N',
    Rarity: 5,
    Size: '5-10',
    Qualities: 'Tractor 4',
    Source: 'All Core',
  },
  {
    Name: 'Turbolaser (Heavy)',
    Skill: 'Gunnery',
    Range: 'Long',
    Dam: '11',
    Crit: '3',
    Price: '20,000',
    Restricted: 'Y',
    Rarity: 8,
    Size: '6-10',
    Qualities: 'Breach 4, Slow-Firing 2',
    Source: 'All Core',
  },
  {
    Name: 'Turbolaser (Light)',
    Skill: 'Gunnery',
    Range: 'Medium',
    Dam: '9',
    Crit: '3',
    Price: '12,000',
    Restricted: 'Y',
    Rarity: 7,
    Size: '5-10',
    Qualities: 'Breach 2, Slow-Firing 1',
    Source: 'All Core',
  },
  {
    Name: 'Turbolaser (Medium)',
    Skill: 'Gunnery',
    Range: 'Long',
    Dam: '10',
    Crit: '3',
    Price: '15,000',
    Restricted: 'Y',
    Rarity: 7,
    Size: '6-10',
    Qualities: 'Breach 3, Slow Firing 1',
    Source: 'All Core',
  },
  {
    Name: 'Unguided Rocket',
    Skill: 'Gunnery',
    Range: 'Short',
    Dam: '5',
    Crit: '3',
    Price: '300',
    Restricted: 'N',
    Rarity: 4,
    Size: '',
    Qualities: 'Blast 3, Breach 3, Slow-Firing 1',
    Source: 'SWE08',
  },
  {
    Name: 'Unguided Rocket (mini)',
    Skill: 'Gunnery',
    Range: 'Close',
    Dam: '3',
    Crit: '4',
    Price: '250',
    Restricted: 'N',
    Rarity: 4,
    Size: '',
    Qualities: 'Blast 1, Breach 2, Slow-Firing 1',
    Source: 'SWE08',
  },
];

export default weapons;
